---
- name: Packages - Install generic useful packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - nc
    - git
    - lsof
    - screen
    - telnet
    - wget
    - sysstat
    - rsync
    - bash-completion
    - bind-utils
    - lvm3
  tags:
    - generic

- name: Selinux - Install libselinux-python package
  yum: name=libselinux-python state=present
  tags: selinux

- name: Selinux - Set SELinux policy and state
  selinux: state=disabled
  tags: selinux

- name: Users - Configure members of wheel group for passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    state: present
  tags:
    - users

- name: Timezone - Set timezone to etc/utc
  become: true
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

- name: Swap - Allocate swap
  command: |
    dd if=/dev/zero of={{ swap_location }} count={{ swap_size }} bs=1MiB creates={{ swap_location }}
  register: allocate_swap
  when: swap_size != false

- name: Swap - Set permissions
  file: path={{ swap_location }} mode=600
  when: swap_size != false

- name: Swap - Setup swap
  command: mkswap {{ swap_location }}
  register: setup_swap
  when: swap_size != false and allocate_swap.changed

- name: Swap -Enable swap
  command: swapon {{ swap_location }}
  when: swap_size != false and allocate_swap.changed

- name: Swap -Add swap to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swap_location }}   none    swap    sw    0   0" state=present
  when: swap_size != false
